name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: |
          npm install

      - name: Lint
        run: |
          npm run eslint
          npm run stylelint
          npm run tsc

      - name: Build
        run: |
          npm run build

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          personal_token: ${{ secrets.ACCESS_TOKEN }}
#          publish_dir: ./dist
